In [1]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pprint as pp

In [2]:
# Import data
links = pd.read_csv('Resources/ml-latest-small/links.csv')
movies = pd.read_csv('Resources/ml-latest-small/movies.csv')
ratings = pd.read_csv('Resources/ml-latest-small/ratings.csv')
tags = pd.read_csv('Resources/ml-latest-small/tags.csv')

In [3]:
print("Links columns: ", links.columns)
print("Movies columns: ", movies.columns)
print("Ratings columns: ", ratings.columns)
print("Tags columns: ", tags.columns)

Links columns:  Index(['movieId', 'imdbId', 'tmdbId'], dtype='object')
Movies columns:  Index(['movieId', 'title', 'genres'], dtype='object')
Ratings columns:  Index(['userId', 'movieId', 'rating', 'timestamp'], dtype='object')
Tags columns:  Index(['userId', 'movieId', 'tag', 'timestamp'], dtype='object')

In [4]:
ratings_sorted = ratings.sort_values(by=['userId'], ascending=True)
tags_sorted = tags.sort_values(by=['userId'], ascending=True)

print(ratings_sorted.head().to_string())
print(tags_sorted.head().to_string())

     userId  movieId  rating  timestamp
0         1        1     4.0  964982703
147       1     2329     5.0  964983263
148       1     2338     2.0  964983546
149       1     2353     5.0  964983861
150       1     2366     4.0  964982462
   userId  movieId                tag   timestamp
0       2    60756              funny  1445714994
7       2   106782  Leonardo DiCaprio  1445715051
6       2   106782              drugs  1445715054
5       2    89774          Tom Hardy  1445715205
8       2   106782    Martin Scorsese  1445715056

In [5]:
# Merge the combined ratings_tags DataFrame with movies DataFrame
all_data = pd.merge(ratings_sorted, tags_sorted, on='movieId', how='inner')

# Verify the merged DataFrame
all_data.head(20)

# Save all_data DataFrame to a CSV file
all_data.to_csv('Resources/all_data.csv', index=False)

In [6]:
# Step 1: Identify mismatched rows
mismatched_rows = all_data[all_data['userId_x'] != all_data['userId_y']]

# Print mismatched rows to investigate
# print(mismatched_rows.to_string())

# Step 2: Update userId_y to match userId_x for mismatched rows
all_data.loc[all_data['userId_x'] != all_data['userId_y'], 'userId_y'] = all_data['userId_x']

# Verify that there are no more mismatched rows
mismatched_rows_after = all_data[all_data['userId_x'] != all_data['userId_y']]
print(mismatched_rows_after.to_string())  # This should print an empty DataFrame

# Display the cleaned DataFrame
print(all_data.head(20).to_string())

Empty DataFrame
Columns: [userId_x, movieId, rating, timestamp_x, userId_y, tag, timestamp_y]
Index: []
    userId_x  movieId  rating  timestamp_x  userId_y                 tag  timestamp_y
0          1        1     4.0    964982703         1               pixar   1139045764
1          1        1     4.0    964982703         1               pixar   1137206825
2          1        1     4.0    964982703         1                 fun   1525286013
3          1     2329     5.0    964983263         1   thought-provoking   1457843729
4          1     2329     5.0    964983263         1              racism   1138031951
5          1     2329     5.0    964983263         1            politics   1424141461
6          1     2329     5.0    964983263         1           emotional   1424141459
7          1     2329     5.0    964983263         1       edward norton   1424141449
8          1     2387     5.0    964983123         1         dark comedy   1474382225
9          1     2387     5.0    964983123         1          dark humor   1474382223
10         1     2470     5.0    964982588         1           Australia   1137374348
11         1     2502     5.0    964981278         1             stapler   1138032123
12         1     2502     5.0    964981278         1           workplace   1138032129
13         1     2529     5.0    964982242         1        twist ending   1138032140
14         1     2571     5.0    964981888         1              sci-fi   1457842899
15         1     2571     5.0    964981888         1        martial arts   1457842912
16         1     2571     5.0    964981888         1  alternate universe   1137204991
17         1     2571     5.0    964981888         1    post apocalyptic   1424141101
18         1     2571     5.0    964981888         1          philosophy   1424141098
19         1     2616     4.0    964983080         1          comic book   1234789098

In [7]:
ratings.head(20)

    userId  movieId  rating  timestamp
0        1        1     4.0  964982703
1        1        3     4.0  964981247
2        1        6     4.0  964982224
3        1       47     5.0  964983815
4        1       50     5.0  964982931
5        1       70     3.0  964982400
6        1      101     5.0  964980868
7        1      110     4.0  964982176
8        1      151     5.0  964984041
9        1      157     5.0  964984100
10       1      163     5.0  964983650
11       1      216     5.0  964981208
12       1      223     3.0  964980985
13       1      231     5.0  964981179
14       1      235     4.0  964980908
15       1      260     5.0  964981680
16       1      296     3.0  964982967
17       1      316     3.0  964982310
18       1      333     5.0  964981179
19       1      349     4.0  964982563

In [8]:
# Count unique values in tags csv
print(tags['tag'].value_counts())

tag
In Netflix queue     131
atmospheric           36
thought-provoking     24
superhero             24
funny                 23
                    ...
small towns            1
In Your Eyes           1
Lloyd Dobbler          1
weak plot              1
Heroic Bloodshed       1
Name: count, Length: 1589, dtype: int64

In [9]:
# Reload the DataFrame from the original CSV file
all_data = pd.read_csv('Resources/all_data.csv')

# Verify the columns are restored
print(all_data.columns)

# Update column names in all_data DataFrame
all_data = all_data.rename(columns={
    'userId_x': 'userId_Rating', 
    'userId_y': 'userId_Tags', 
    'timestamp_x': 'timestamp_Rating', 
    'timestamp_y': 'timestamp_Tags'
})


# Verify the columns are updated
print(all_data.columns)

Index(['userId_x', 'movieId', 'rating', 'timestamp_x', 'userId_y', 'tag',
       'timestamp_y'],
      dtype='object')
Index(['userId_Rating', 'movieId', 'rating', 'timestamp_Rating', 'userId_Tags',
       'tag', 'timestamp_Tags'],
      dtype='object')

In [10]:
# Adding movie titles to all_data DataFrame
all_data_incl_movies = pd.merge(all_data, movies, on='movieId', how='inner')

# Sort the DataFrame by both userId_Rating and userId_Tags
sorted_df = all_data_incl_movies.sort_values(by=['userId_Rating', 'userId_Tags'], ascending=True)

# Display the first 20 rows of the sorted DataFrame
sorted_df.head(20)

,userId_Rating,movieId,rating,timestamp_Rating,userId_Tags,tag,timestamp_Tags,title,genres
53,1,3578,5.0,964980668,62,Russell Crowe,1528152465,Gladiator (2000),Action|Adventure|Drama
54,1,3578,5.0,964980668,62,Rome,1528152463,Gladiator (2000),Action|Adventure|Drama
55,1,3578,5.0,964980668,62,revenge,1528152496,Gladiator (2000),Action|Adventure|Drama
56,1,3578,5.0,964980668,62,imdb top 250,1528152498,Gladiator (2000),Action|Adventure|Drama
57,1,3578,5.0,964980668,62,history,1528152467,Gladiator (2000),Action|Adventure|Drama
58,1,3578,5.0,964980668,62,Epic,1528152469,Gladiator (2000),Action|Adventure|Drama
59,1,3578,5.0,964980668,62,ancient Rome,1528152504,Gladiator (2000),Action|Adventure|Drama
218,1,110,4.0,964982176,62,sword fight,1528152535,Braveheart (1995),Action|Drama|War
219,1,110,4.0,964982176,62,revenge,1528152531,Braveheart (1995),Action|Drama|War
220,1,110,4.0,964982176,62,Oscar (Best Cinematography),1528152539,Braveheart (1995),Action|Drama|War
221,1,110,4.0,964982176,62,mel gibson,1528152521,Braveheart (1995),Action|Drama|War
222,1,110,4.0,964982176,62,Medieval,1528152528,Braveheart (1995),Action|Drama|War
223,1,110,4.0,964982176,62,inspirational,1528152527,Braveheart (1995),Action|Drama|War
224,1,110,4.0,964982176,62,historical,1528152523,Braveheart (1995),Action|Drama|War
225,1,110,4.0,964982176,62,epic,1528152532,Braveheart (1995),Action|Drama|War
226,1,110,4.0,964982176,62,beautiful scenery,1528152541,Braveheart (1995),Action|Drama|War
238,1,260,5.0,964981680,63,space action,1443199710,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi
239,1,260,5.0,964981680,63,classic,1443199698,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi
240,1,260,5.0,964981680,76,action,1439165594,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi
241,1,260,5.0,964981680,76,sci-fi,1439165588,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi

In [11]:
year_rated = 1970 + (sorted_df['timestamp_Rating'] / 31540000)
year_rated = year_rated.astype('int')
sorted_df['year_rated'] = year_rated
sorted_df.head(20)

,userId_Rating,movieId,rating,timestamp_Rating,userId_Tags,tag,timestamp_Tags,title,genres,year_rated
53,1,3578,5.0,964980668,62,Russell Crowe,1528152465,Gladiator (2000),Action|Adventure|Drama,2000
54,1,3578,5.0,964980668,62,Rome,1528152463,Gladiator (2000),Action|Adventure|Drama,2000
55,1,3578,5.0,964980668,62,revenge,1528152496,Gladiator (2000),Action|Adventure|Drama,2000
56,1,3578,5.0,964980668,62,imdb top 250,1528152498,Gladiator (2000),Action|Adventure|Drama,2000
57,1,3578,5.0,964980668,62,history,1528152467,Gladiator (2000),Action|Adventure|Drama,2000
58,1,3578,5.0,964980668,62,Epic,1528152469,Gladiator (2000),Action|Adventure|Drama,2000
59,1,3578,5.0,964980668,62,ancient Rome,1528152504,Gladiator (2000),Action|Adventure|Drama,2000
218,1,110,4.0,964982176,62,sword fight,1528152535,Braveheart (1995),Action|Drama|War,2000
219,1,110,4.0,964982176,62,revenge,1528152531,Braveheart (1995),Action|Drama|War,2000
220,1,110,4.0,964982176,62,Oscar (Best Cinematography),1528152539,Braveheart (1995),Action|Drama|War,2000
221,1,110,4.0,964982176,62,mel gibson,1528152521,Braveheart (1995),Action|Drama|War,2000
222,1,110,4.0,964982176,62,Medieval,1528152528,Braveheart (1995),Action|Drama|War,2000
223,1,110,4.0,964982176,62,inspirational,1528152527,Braveheart (1995),Action|Drama|War,2000
224,1,110,4.0,964982176,62,historical,1528152523,Braveheart (1995),Action|Drama|War,2000
225,1,110,4.0,964982176,62,epic,1528152532,Braveheart (1995),Action|Drama|War,2000
226,1,110,4.0,964982176,62,beautiful scenery,1528152541,Braveheart (1995),Action|Drama|War,2000
238,1,260,5.0,964981680,63,space action,1443199710,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi,2000
239,1,260,5.0,964981680,63,classic,1443199698,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi,2000
240,1,260,5.0,964981680,76,action,1439165594,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi,2000
241,1,260,5.0,964981680,76,sci-fi,1439165588,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi,2000

In [12]:
year_tagged = 1970 + (sorted_df['timestamp_Tags'] / 31540000)
year_tagged = year_tagged.astype('int')
sorted_df['year_tagged'] = year_tagged
sorted_df.head(20)

,userId_Rating,movieId,rating,timestamp_Rating,userId_Tags,tag,timestamp_Tags,title,genres,year_rated,year_tagged
53,1,3578,5.0,964980668,62,Russell Crowe,1528152465,Gladiator (2000),Action|Adventure|Drama,2000,2018
54,1,3578,5.0,964980668,62,Rome,1528152463,Gladiator (2000),Action|Adventure|Drama,2000,2018
55,1,3578,5.0,964980668,62,revenge,1528152496,Gladiator (2000),Action|Adventure|Drama,2000,2018
56,1,3578,5.0,964980668,62,imdb top 250,1528152498,Gladiator (2000),Action|Adventure|Drama,2000,2018
57,1,3578,5.0,964980668,62,history,1528152467,Gladiator (2000),Action|Adventure|Drama,2000,2018
58,1,3578,5.0,964980668,62,Epic,1528152469,Gladiator (2000),Action|Adventure|Drama,2000,2018
59,1,3578,5.0,964980668,62,ancient Rome,1528152504,Gladiator (2000),Action|Adventure|Drama,2000,2018
218,1,110,4.0,964982176,62,sword fight,1528152535,Braveheart (1995),Action|Drama|War,2000,2018
219,1,110,4.0,964982176,62,revenge,1528152531,Braveheart (1995),Action|Drama|War,2000,2018
220,1,110,4.0,964982176,62,Oscar (Best Cinematography),1528152539,Braveheart (1995),Action|Drama|War,2000,2018
221,1,110,4.0,964982176,62,mel gibson,1528152521,Braveheart (1995),Action|Drama|War,2000,2018
222,1,110,4.0,964982176,62,Medieval,1528152528,Braveheart (1995),Action|Drama|War,2000,2018
223,1,110,4.0,964982176,62,inspirational,1528152527,Braveheart (1995),Action|Drama|War,2000,2018
224,1,110,4.0,964982176,62,historical,1528152523,Braveheart (1995),Action|Drama|War,2000,2018
225,1,110,4.0,964982176,62,epic,1528152532,Braveheart (1995),Action|Drama|War,2000,2018
226,1,110,4.0,964982176,62,beautiful scenery,1528152541,Braveheart (1995),Action|Drama|War,2000,2018
238,1,260,5.0,964981680,63,space action,1443199710,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi,2000,2015
239,1,260,5.0,964981680,63,classic,1443199698,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi,2000,2015
240,1,260,5.0,964981680,76,action,1439165594,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi,2000,2015
241,1,260,5.0,964981680,76,sci-fi,1439165588,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi,2000,2015

In [13]:
# Dropping timestamp columns
sorted_df = sorted_df.drop(columns=['timestamp_Rating', 'timestamp_Tags'])
sorted_df.head(20)

,userId_Rating,movieId,rating,userId_Tags,tag,title,genres,year_rated,year_tagged
53,1,3578,5.0,62,Russell Crowe,Gladiator (2000),Action|Adventure|Drama,2000,2018
54,1,3578,5.0,62,Rome,Gladiator (2000),Action|Adventure|Drama,2000,2018
55,1,3578,5.0,62,revenge,Gladiator (2000),Action|Adventure|Drama,2000,2018
56,1,3578,5.0,62,imdb top 250,Gladiator (2000),Action|Adventure|Drama,2000,2018
57,1,3578,5.0,62,history,Gladiator (2000),Action|Adventure|Drama,2000,2018
58,1,3578,5.0,62,Epic,Gladiator (2000),Action|Adventure|Drama,2000,2018
59,1,3578,5.0,62,ancient Rome,Gladiator (2000),Action|Adventure|Drama,2000,2018
218,1,110,4.0,62,sword fight,Braveheart (1995),Action|Drama|War,2000,2018
219,1,110,4.0,62,revenge,Braveheart (1995),Action|Drama|War,2000,2018
220,1,110,4.0,62,Oscar (Best Cinematography),Braveheart (1995),Action|Drama|War,2000,2018
221,1,110,4.0,62,mel gibson,Braveheart (1995),Action|Drama|War,2000,2018
222,1,110,4.0,62,Medieval,Braveheart (1995),Action|Drama|War,2000,2018
223,1,110,4.0,62,inspirational,Braveheart (1995),Action|Drama|War,2000,2018
224,1,110,4.0,62,historical,Braveheart (1995),Action|Drama|War,2000,2018
225,1,110,4.0,62,epic,Braveheart (1995),Action|Drama|War,2000,2018
226,1,110,4.0,62,beautiful scenery,Braveheart (1995),Action|Drama|War,2000,2018
238,1,260,5.0,63,space action,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi,2000,2015
239,1,260,5.0,63,classic,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi,2000,2015
240,1,260,5.0,76,action,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi,2000,2015
241,1,260,5.0,76,sci-fi,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi,2000,2015

In [14]:
sorted_df['year_released'] = sorted_df['title'].str.extract(r'\((\d{4})\)')
sorted_df.tail()

,userId_Rating,movieId,rating,userId_Tags,tag,title,genres,year_rated,year_tagged,year_released
232792,610,1732,4.5,599,Nudity (Full Frontal),"Big Lebowski, The (1998)",Comedy|Crime,2016,2017,1998
232096,610,3578,5.0,606,Romans,Gladiator (2000),Action|Adventure|Drama,2017,2007,2000
231909,610,168248,5.0,610,Heroic Bloodshed,John Wick: Chapter Two (2017),Action|Crime|Thriller,2017,2017,2017
232177,610,3265,5.0,610,gun fu,Hard-Boiled (Lat sau san taam) (1992),Action|Crime|Drama|Thriller,2016,2017,1992
232178,610,3265,5.0,610,heroic bloodshed,Hard-Boiled (Lat sau san taam) (1992),Action|Crime|Drama|Thriller,2016,2017,1992

In [15]:
# Saving updated CSV file
sorted_df.to_csv('Resources/sorted_data.csv', index=False)

In [16]:
# check year released dtype and change to categorical if needed
# merged_movie_ratings.dtypes
sorted_df['year_released'] = sorted_df['year_released'].astype('category')
sorted_df['year_rated'] = sorted_df['year_rated'].astype('category')
sorted_df['year_tagged'] = sorted_df['year_tagged'].astype('category')
sorted_df.dtypes

userId_Rating       int64
movieId             int64
rating            float64
userId_Tags         int64
tag                object
title              object
genres             object
year_rated       category
year_tagged      category
year_released    category
dtype: object

In [17]:
# Convert categorical data to numeric with `pd.get_dummies`
sorted_df_copy =  sorted_df.copy()
merged_dummies = pd.get_dummies(sorted_df_copy, columns=['year_rated', 'year_released', 'genres', 'year_tagged'] \
                                , drop_first=True)

merged_dummies.head()

,userId_Rating,movieId,rating,userId_Tags,tag,title,year_rated_1997,year_rated_1998,year_rated_1999,year_rated_2000,...,year_tagged_2009,year_tagged_2010,year_tagged_2011,year_tagged_2012,year_tagged_2013,year_tagged_2014,year_tagged_2015,year_tagged_2016,year_tagged_2017,year_tagged_2018
53,1,3578,5.0,62,Russell Crowe,Gladiator (2000),False,False,False,True,...,False,False,False,False,False,False,False,False,False,True
54,1,3578,5.0,62,Rome,Gladiator (2000),False,False,False,True,...,False,False,False,False,False,False,False,False,False,True
55,1,3578,5.0,62,revenge,Gladiator (2000),False,False,False,True,...,False,False,False,False,False,False,False,False,False,True
56,1,3578,5.0,62,imdb top 250,Gladiator (2000),False,False,False,True,...,False,False,False,False,False,False,False,False,False,True
57,1,3578,5.0,62,history,Gladiator (2000),False,False,False,True,...,False,False,False,False,False,False,False,False,False,True

In [18]:
# drop a couple more columns
merged_dummies = merged_dummies.drop(columns=['userId_Rating', 'movieId', 'userId_Tags', 'title'])
merged_dummies.head()

,rating,tag,year_rated_1997,year_rated_1998,year_rated_1999,year_rated_2000,year_rated_2001,year_rated_2002,year_rated_2003,year_rated_2004,...,year_tagged_2009,year_tagged_2010,year_tagged_2011,year_tagged_2012,year_tagged_2013,year_tagged_2014,year_tagged_2015,year_tagged_2016,year_tagged_2017,year_tagged_2018
53,5.0,Russell Crowe,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
54,5.0,Rome,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
55,5.0,revenge,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
56,5.0,imdb top 250,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
57,5.0,history,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [19]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.preprocessing import StandardScaler

# Split our preprocessed data into our features and target arrays
y = merged_dummies['rating']
X = merged_dummies.drop(['rating'], axis=1)

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [20]:
from sklearn.preprocessing import LabelEncoder

# Instantiate the LabelEncoder
label_encoder = LabelEncoder()

# Combine X_train and X_test for fitting the LabelEncoder
combined_data = pd.concat([X_train, X_test])

# Fit the LabelEncoder on the combined data
for column in combined_data.columns:
    if combined_data[column].dtype == object:
        combined_data[column] = combined_data[column].astype(str)  # Convert column values to strings
        label_encoder.fit(combined_data[column])

# Transform X_train and X_test using the fitted LabelEncoder
for column in X_train.columns:
    if X_train[column].dtype == object:
        X_train[column] = label_encoder.transform(X_train[column])
        X_test[column] = label_encoder.transform(X_test[column])

In [21]:
# Instantiate the model with k = 3 neighbors
model = KNeighborsClassifier(n_neighbors=3)

In [22]:
# Convert continuous target variable to discrete classes
y_train_classes = pd.cut(y_train, bins=[0, 1, 2, 3, 4, 5], labels=False)

# Train the model with the converted target variable
model.fit(X_train, y_train_classes)

KNeighborsClassifier(n_neighbors=3)

In [23]:
import numpy as np
from scipy.sparse import csr_matrix
consolidated_movies_df = pd.read_csv('consolidated_movies.csv')
def create_X(consolidated_movies_df):
    """
    Generates a sparse matrix from ratings dataframe.
    
    Args:
        consolidated_movies_df: pandas dataframe containing columns (userId, movieId, rating)
    
    Returns:
        X: sparse matrix
        user_mapper: dict mapping user id's to user indices
        user_inv_mapper: dict mapping user indices to user id's
        movie_mapper: dict mapping movie id's to movie indices
        movie_inv_mapper: dict mapping movie indices to movie id's
    """
    # Number of unique users and movies
    M = consolidated_movies_df['userId'].nunique()
    N = consolidated_movies_df['movieId'].nunique()

    # Mapping dictionaries
    user_mapper = dict(zip(np.unique(consolidated_movies_df["userId"]), list(range(M))))
    movie_mapper = dict(zip(np.unique(consolidated_movies_df["movieId"]), list(range(N))))
    
    user_inv_mapper = dict(zip(list(range(M)), np.unique(consolidated_movies_df["userId"])))
    movie_inv_mapper = dict(zip(list(range(N)), np.unique(consolidated_movies_df["movieId"])))
    
    # Map user and movie IDs to their matrix indices
    user_index = [user_mapper[i] for i in consolidated_movies_df['userId']]
    item_index = [movie_mapper[i] for i in consolidated_movies_df['movieId']]

    # Create the sparse matrix
    X = csr_matrix((consolidated_movies_df["rating"], (user_index, item_index)), shape=(M, N))
    
    return X, user_mapper, movie_mapper, user_inv_mapper, movie_inv_mapper

# Example usage
X, user_mapper, movie_mapper, user_inv_mapper, movie_inv_mapper = create_X(consolidated_movies_df)

In [24]:
from sklearn.neighbors import NearestNeighbors

def find_similar_movies(movie_id, X, movie_mapper, movie_inv_mapper, k, metric='cosine'):
    """
    Finds k-nearest neighbors for a given movie id.
    
    Args:
        movie_id: id of the movie of interest
        X: user-item utility matrix
        k: number of similar movies to retrieve
        metric: distance metric for kNN calculations
    
    Output: returns list of k similar movie ID's
    """
    X = X.T
    neighbour_ids = []
    
    movie_ind = movie_mapper[movie_id]
    movie_vec = X[movie_ind]
    if isinstance(movie_vec, (np.ndarray)):
        movie_vec = movie_vec.reshape(1,-1)
    # use k+1 since kNN output includes the movieId of interest
    kNN = NearestNeighbors(n_neighbors=k+1, algorithm="brute", metric=metric)
    kNN.fit(X)
    neighbour = kNN.kneighbors(movie_vec, return_distance=False)
    for i in range(0,k):
        n = neighbour.item(i)
        neighbour_ids.append(movie_inv_mapper[n])
    neighbour_ids.pop(0)
    return neighbour_ids

In [25]:
# def print_similar_movies(movie_id, X, movie_mapper, movie_inv_mapper, movie_titles, metric='cosine', k=4):
#     # Find similar movies
#     similar_movies = find_similar_movies(movie_id, X, movie_mapper, movie_inv_mapper, metric=metric, k=k)
    
#     # Get the title of the input movie
#     movie_title = movie_titles[movie_id]
    
#     # Print the title of the input movie
#     print(f"Because you watched {movie_title}:")
    
#     # Print the titles of the similar movies
#     for i in similar_movies:
#         print(movie_titles[i])

# # Example usage with different movie IDs
# movie_titles = dict(zip(consolidated_movies_df['movieId'], consolidated_movies_df['title']))

# # # Test with movie_id = 1
# # print_similar_movies(1, X, movie_mapper, movie_inv_mapper, movie_titles)

# # Test with another movie_id, e.g., movie_id = 2
# print_similar_movies(12, X, movie_mapper, movie_inv_mapper, movie_titles)

# # # Test with another movie_id, e.g., movie_id = 3
# # print_similar_movies(3, X, movie_mapper, movie_inv_mapper, movie_titles)

In [26]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

data = pd.read_csv('consolidated_movies.csv')

# Create a movie-item matrix
movie_item_matrix = data.pivot(index='movieId', columns='userId', values='rating').fillna(0)

# Normalize the data
scaler = StandardScaler()
movie_item_matrix_normalized = scaler.fit_transform(movie_item_matrix)

In [27]:
# Assuming you have additional features like genres
# One-hot encode the genres
movies['genres'] = movies['genres'].str.split('|')
movies = movies.explode('genres')
movies = pd.get_dummies(movies, columns=['genres'])

# Merge with the movie-item matrix
movie_features = pd.merge(movie_item_matrix, movies, on='movieId')

In [28]:
# # Initialize the KNN model
# knn = KNeighborsClassifier()

# # Perform grid search
# grid_search = GridSearchCV(knn, param_grid, cv=5)
# grid_search.fit(movie_item_matrix_normalized, y)  # Provide the target variable y

# # Get the best parameters
# best_params = grid_search.best_params_
# print(best_params)

In [29]:
# from sklearn.neighbors import NearestNeighbors

# # Fit the KNN model
# knn_model = NearestNeighbors(metric='cosine', algorithm='brute')
# knn_model.fit(movie_item_matrix_sparse)

In [30]:
def find_similar_movies(movie_id, X, movie_mapper, movie_inv_mapper, metric='cosine', k=4):
    # Get the index of the movie in the movie-item matrix
    movie_index = movie_mapper[movie_id]
    
    # Find the k nearest neighbors for the movie
    distances, indices = knn_model.kneighbors(X[movie_index], n_neighbors=k+1)
    
    # Get the movie indices for the k nearest neighbors
    similar_movies = indices.flatten()[1:]
    
    # Map indices back to movie IDs
    similar_movie_ids = [movie_inv_mapper[i] for i in similar_movies]
    
    return similar_movie_ids

In [31]:
# def print_similar_movies(movie_id, X, movie_mapper, movie_inv_mapper, movie_titles, metric='cosine', k=4):
#     # Find similar movies
#     similar_movies = find_similar_movies(movie_id, X, movie_mapper, movie_inv_mapper, metric=metric, k=k)
    
#     # Get the title of the input movie
#     movie_title = movie_titles[movie_id]
    
#     # Print the title of the input movie
#     print(f"Because you watched {movie_title}:")
    
#     # Print the titles of the similar movies
#     for i in similar_movies:
#         print(movie_titles[i])

# # Example usage with different movie IDs
# movie_titles = dict(zip(consolidated_movies_df['movieId'], consolidated_movies_df['title']))

# # Test with a movie_id, e.g., movie_id = 12
# print_similar_movies(39, movie_item_matrix_sparse, movie_mapper, movie_inv_mapper, movie_titles)

In [32]:
consolidated_movies_df.columns

Index(['movieId', 'title', 'genres', 'release_year', 'userId', 'rating',
       'timestamp', 'rating_year'],
      dtype='object')

In [33]:
# from sklearn.metrics.pairwise import cosine_similarity
# from sklearn.preprocessing import LabelEncoder

# # Assuming you have a DataFrame 'movies' with movie features
# # Compute the cosine similarity matrix using the relevant feature columns
# features = consolidated_movies_df[['title', 'genres', 'rating']]

# # Encode the categorical features
# label_encoder = LabelEncoder()
# for column in features.columns:
#     if features[column].dtype == object:
#         features[column] = label_encoder.fit_transform(features[column])

# # Compute the cosine similarity matrix
# cosine_sim = cosine_similarity(features)
# return movie_titles.iloc[movie_indices]

# # Example usage
# movie_titles = movies[['movieId', 'title']]
# recommendations = content_based_recommendations(12, cosine_sim, movie_titles)
# print(recommendations)
# # Function to get movie recommendations
# def content_based_recommendations(movie_id, cosine_sim, movie_titles, k=10):
#     # Get the index of the movie
#     idx = movie_titles.index[movie_titles['movieId'] == movie_id].tolist()[0]
    
#     # Get the pairwise similarity scores
#     sim_scores = list(enumerate(cosine_sim[idx]))
    
#     # Sort the movies based on similarity scores
#     sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    
#     # Get the scores of the k most similar movies
#     sim_scores = sim_scores[1:k+1]
    
#     # Get the movie indices
#     movie_indices = [i[0] for i in sim_scores]
    
#     # Return the top k most similar movies
#     return movie_titles.iloc[movie_indices]

# # Example usage
# movie_titles = movies[['movieId', 'title']]
# recommendations = content_based_recommendations(12, cosine_sim, movie_titles)
# print(recommendations)

In [35]:
# from surprise import Dataset, Reader, SVD, accuracy
# from surprise.model_selection import train_test_split
# import pandas as pd

# # Load the data into Surprise format
# movies = pd.read_csv('consolidated_movies.csv')
# reader = Reader(rating_scale=(1, 5))
# data = Dataset.load_from_df(movies[['userId', 'movieId', 'rating']], reader)
# movie_titles = movies[['title', 'movieId']]
# # Split the data into training and test sets
# trainset, testset = train_test_split(data, test_size=0.25)

# # Use SVD for collaborative filtering
# algo = SVD()
# algo.fit(trainset)

# # Function to get movie recommendations for multiple movies
# def collaborative_filtering_recommendations(user_id, movie_ids, algo, movie_titles, k=10):
#     recommendations = {}
    
#     for movie_id in movie_ids:
#         # Predict ratings for all movies except the current one
#         all_movie_ids = movies['movieId'].unique()
#         predictions = [algo.predict(user_id, mid) for mid in all_movie_ids if mid != movie_id]
        
#         # Sort the predictions based on estimated rating
#         predictions = sorted(predictions, key=lambda x: x.est, reverse=True)
        
#         # Get the top k recommendations
#         top_k_predictions = predictions[:k]
        
#         # Get the movie titles for the top k recommendations
#         top_k_movie_ids = [pred.iid for pred in top_k_predictions]
#         top_k_movie_titles = movie_titles[movie_titles['movieId'].isin(top_k_movie_ids)]
        
#         # Remove duplicates
#         top_k_movie_titles = top_k_movie_titles.drop_duplicates(subset='title')
        
#         recommendations[movie_id] = top_k_movie_titles.head(k)
    
#     return recommendations

# # Function to evaluate the model
# def evaluate_model(algo, testset):
#     predictions = algo.test(testset)
#     rmse = accuracy.rmse(predictions)
#     return rmse

# # Example usage
# if movie_id in movie_titles['movieId'].values:
#     movie_title = movie_titles[movie_titles['movieId'] == movie_id]['title'].values[0]
#     print(f"Recommendations for '{movie_title}':")
#     for index, row in recs.iterrows():
#         print(f" - {row['title']}")
# else:
#     print(f"Movie with ID {movie_id} not found in movie_titles dataframe.")

In [36]:
from sklearn.decomposition import NMF

# Create a user-item matrix
user_item_matrix = ratings.pivot(index='userId', columns='movieId', values='rating').fillna(0)

# Apply NMF
nmf = NMF(n_components=20)
user_factors = nmf.fit_transform(user_item_matrix)
item_factors = nmf.components_

# Function to get movie recommendations based on a movie
def matrix_factorization_recommendations(movie_id, item_factors, movie_titles, k=10):
    # Get the movie's latent factors
    movie_index = user_item_matrix.columns.get_loc(movie_id)
    movie_vector = item_factors[:, movie_index]
    
    # Compute the similarity scores for all movies
    scores = item_factors.T.dot(movie_vector)
    
    # Get the top k movie indices
    top_k_indices = scores.argsort()[-k-1:][::-1]  # -1 to exclude the movie itself
    
    # Exclude the movie itself from the recommendations
    top_k_indices = top_k_indices[top_k_indices != movie_index]
    
    # Get the movie titles for the top k recommendations
    top_k_movie_ids = user_item_matrix.columns[top_k_indices]
    top_k_movie_titles = movie_titles[movie_titles['movieId'].isin(top_k_movie_ids)]
    
    # Remove duplicates
    top_k_movie_titles = top_k_movie_titles.drop_duplicates(subset='title')
    
    return top_k_movie_titles.head(k)

# Example usage
movie_id_to_check = 39  # Specify the movie ID for which you want recommendations
recommendations = matrix_factorization_recommendations(movie_id_to_check, item_factors, movie_titles)
print(recommendations)

                      title  movieId
0                 Toy Story        1
10019          Forrest Gump      356
10522        Lion King, The      364
13567        Mrs. Doubtfire      500
15468               Aladdin      588
16584  Beauty and the Beast      595
16790          Pretty Woman      597
21988          Mary Poppins     1028
22198   Sound of Music, The     1035
61329                 Shrek     4306

/opt/anaconda3/envs/pythondata/lib/python3.10/site-packages/sklearn/decomposition/_nmf.py:1770: ConvergenceWarning: Maximum number of iterations 200 reached. Increase it to improve convergence.
  warnings.warn(

In [ ]:
# from keras.models import Model
# from keras.layers import Input, Embedding, Flatten, Dot, Dense

# # Define the model
# user_input = Input(shape=(1,))
# movie_input = Input(shape=(1,))
# user_embedding = Embedding(input_dim=num_users, output_dim=50)(user_input)
# movie_embedding = Embedding(input_dim=num_movies, output_dim=50)(movie_input)
# user_vec = Flatten()(user_embedding)
# movie_vec = Flatten()(movie_embedding)
# dot_product = Dot(axes=1)([user_vec, movie_vec])
# output = Dense(1)(dot_product)
# model = Model([user_input, movie_input], output)
# model.compile(optimizer='adam', loss='mean_squared_error')

# # Train the model
# model.fit([ratings['userId'], ratings['movieId']], ratings['rating'], epochs=10, batch_size=64)

# # Function to get movie recommendations
# def deep_learning_recommendations(user_id, model, movie_titles, k=10):
#     # Predict ratings for all movies
#     movie_ids = movie_titles['movieId'].unique()
#     user_ids = [user_id] * len(movie_ids)
#     predictions = model.predict([user_ids, movie_ids])
    
#     # Sort the predictions based on estimated rating
#     top_k_indices = predictions.flatten().argsort()[-k:][::-1]
    
#     # Get the movie titles for the top k recommendations
#     top_k_movie_ids = movie_ids[top_k_indices]
#     top_k_movie_titles = movie_titles[movie_titles['movieId'].isin(top_k_movie_ids)]
    
#     return top_k_movie_titles

# # Example usage
# recommendations = deep_learning_recommendations(1, model, movie_titles)
# print(recommendations)

In [38]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import LabelEncoder

# Assuming you have a DataFrame 'movies' with movie features
# Compute the cosine similarity matrix using the relevant feature columns
features = consolidated_movies_df[['title', 'genres', 'rating']]

# Encode the categorical features
label_encoder = LabelEncoder()
for column in features.columns:
    if features[column].dtype == object:
        features[column] = label_encoder.fit_transform(features[column])

# Compute the cosine similarity matrix
cosine_sim = cosine_similarity(features)
return movie_titles.iloc[movie_indices]

# Example of combining content-based and collaborative filtering
def hybrid_recommendations(user_id, movie_id, content_sim, algo, movie_titles, k=10):
    # Get content-based recommendations
    content_recs = content_based_recommendations(movie_id, content_sim, movie_titles, k)
    
    # Get collaborative filtering recommendations
    collab_recs = collaborative_filtering_recommendations(user_id, movie_id, algo, movie_titles, k)
    
    # Combine the recommendations
    combined_recs = pd.concat([content_recs, collab_recs]).drop_duplicates().head(k)
    
    return combined_recs

# Example usage
recommendations = hybrid_recommendations(1, 12, cosine_sim, algo, movie_titles)
print(recommendations)

/var/folders/7g/thp811pn5dbbwflfnhytf9kr0000gn/T/ipykernel_58260/828800012.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features[column] = label_encoder.fit_transform(features[column])
/var/folders/7g/thp811pn5dbbwflfnhytf9kr0000gn/T/ipykernel_58260/828800012.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features[column] = label_encoder.fit_transform(features[column])

: